> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Exploring Numpy Functions


### In this notebook we will explore the power of Numpy.

Numpy is a Python library that is used for working with arrays. 
Here is a great overview of what Numpy can do courtesy of [w3schools](https://www.w3schools.com/python/numpy_intro.asp). 

- function 1: np.array()
- function 2: np.log()
- function 3: np.append()
- function 4: np.sort()
- function 5: np.concatenate()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [39]:
import numpy as np

## Function 1 - np.array()

np.array - used to create an array by passing a list, tuple, or other array type objects

In [40]:
# Example 1 - np.array()
arr_1 = np.array([1,2,3,4,5,6])
arr_1

array([1, 2, 3, 4, 5, 6])

In Example 1 I passed a list of numbers to np.array() and output an array of the numbers we input

In [9]:
# Example 2 - np.array()
arr_2 = np.array(['cat', 'dog', 'mouse' , 'horse'])
arr_2

array(['cat', 'dog', 'mouse', 'horse'], dtype='<U5')

In Example 2 I passed a list of strings (words) to np.array() and output an array of those strings (words)

In [17]:
# Example 3 - np.array()
arr_3 = np.array([[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr_3

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-17-2f1b627027db>, line 2)

In Example 3 it breaks due to a SyntaxError described above. SyntaxError: closing parenthesis ']' does not match opening parenthesis '('

np.array() is a useful tool especially in Machine Learning when you are seperating your features from target.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

## Function 2 - np.log()

np.log() is used for calculation of the natural logarithm of some number where that number is part of an array

In [18]:
# Example 1 - np.log()
arr_1 = [(1,2,3,4,5,6,7,8,9,10)]
arr_1
log_arr_1 = np.log(arr_1)
log_arr_1

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In Example 1 np.log takes the log of the arr_1 array created.

In [19]:
# Example 2 - np.log()
arr_2 = [[1,2,3],
         [4,5,6],
         [7,8,9]]
arr_2
log_arr_2 = np.log(arr_2)
log_arr_2

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In Example 2 np.log takes the log of the arr_2 array created.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
arr_3 = ([1,2,3])
log_arr_3 = np.log[arr_3]

TypeError: 'numpy.ufunc' object is not subscriptable

The above breaks do to a syntax error. The brackets [] attempt to subscript it. One should use () to call it.

Usually I've used np.log for taking the log value of high numbers in order to normalize data.

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

## Function 3 - np.append()

Add some explanations

In [23]:
# Example 1 - np.append()
arr_1 = np.array(['cat'])
arr_2 = np.array(['dog'])
arr_3 = np.append(arr_1, arr_2)
arr_3

array(['cat', 'dog'], dtype='<U3')

In Example 1 I have two single element arrays 'cat' and 'dog'. By using np.append I am able to combine these separate arrays into one array that includes both 'cat' and 'dog'.

In [34]:
# Example 2 - np.append()
arr_4 = np.array([1,2,3])
arr_5 = np.array([2,3,4])
arr_6 = np.append(arr_4, arr_5, axis=0)
arr_6

array([1, 2, 3, 2, 3, 4])

In [35]:
arr_7 = np.array([[1,2,3], [4,5,6]])
arr_8 = np.append(arr_7, [[5,5,5], [5,5,5]], axis=1)
arr_8

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 5, 5, 5]])

In Example 2 I expored appending on different axis. The first example is along axis = 0, while the second example is along axis = 1.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
arr_9 = (['a,b,c'])
arr_10 = (['a1', 'b1', 'c1'])
arr_11 = np.append(arr_9, arr_10, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

This example breaks because axis 1 is out of bounds for the array of dimension 1. Both are 1 dimensional arrays

np.append() is very useful for combining arrays for analysis.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

## Function 4 - np.sort()

np.sort() is used to sort elements within an array

In [41]:
# Example 1 - np.sort()
arr_1 = np.array([1,2,3,44444,5,5,6,7,1123123])
arr_2 = np.sort(arr_1)
arr_2

array([      1,       2,       3,       5,       5,       6,       7,
         44444, 1123123])

In Example 1 I created an array and sorted it smallest to largest (default) using np.sort()

In [44]:
# Example 2 - np.sort()
arr_3 = np.random.randint(1,1000, 500)
arr_4 = -np.sort(-arr_3)
arr_4

array([999, 999, 997, 995, 994, 994, 994, 993, 993, 990, 989, 982, 977,
       977, 973, 970, 970, 966, 966, 965, 964, 963, 961, 957, 957, 951,
       950, 950, 950, 947, 946, 945, 944, 943, 942, 941, 938, 937, 935,
       933, 931, 929, 926, 918, 915, 909, 909, 909, 906, 901, 898, 897,
       897, 897, 896, 893, 889, 887, 881, 880, 878, 878, 878, 877, 877,
       875, 875, 873, 873, 871, 867, 867, 861, 858, 857, 854, 853, 853,
       852, 851, 848, 843, 842, 842, 841, 839, 839, 836, 835, 834, 828,
       828, 828, 824, 822, 816, 811, 808, 806, 805, 803, 800, 800, 797,
       788, 787, 787, 783, 779, 776, 775, 775, 774, 773, 773, 769, 768,
       767, 766, 763, 762, 759, 758, 758, 755, 755, 755, 748, 744, 743,
       742, 741, 741, 738, 737, 736, 735, 734, 731, 731, 731, 730, 729,
       727, 724, 724, 722, 721, 720, 717, 716, 715, 714, 709, 707, 706,
       703, 702, 702, 700, 698, 694, 691, 691, 691, 691, 688, 686, 685,
       683, 680, 678, 673, 670, 667, 667, 665, 662, 661, 660, 65

In Example 2 I used random.randint function and created a random list of numbers bewteen 1 and 1000 (exluding 1, 1000) and sorted them from highest to lowest value. 

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
arr_5 = ([1,2,3,4, 'a'])
arr_6 = np.sort(min(arr_5))
arr_6

TypeError: '<' not supported between instances of 'str' and 'int'

Here the code breaks because the types in the array are different, str and int.

np.sort() is a good function to sort value in an array

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

## Function 5 - np.concatenate()

np.concatenate() is a function that will concatenate a sequence of arrays along a specified axis

In [54]:
# Example 1 - np.concatenate()
arr_1 = np.array([1,2,3])
arr_2 = np.array([1,2,3])
np.concatenate((arr_1, arr_2), axis=0)

array([1, 2, 3, 1, 2, 3])

In Example 1 I concatenated 2 arrays on axis 0 to produce a singular array

In [57]:
# Example 2 - working
arr_1 = np.array([[1,2,3],
                 [1,2,3]])
arr_2 = np.array([[1,2,3],
                 [1,2,3]])
np.concatenate((arr_1, arr_2), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In Example 2 I concatenated 2, 2D arrays on axis = 1 to create a new 2D array

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
arr_1 = np.array([1,2,3])
arr_2 = np.array([1,2,3])
np.concatenate((arr_1, arr_2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

Since the array is of 1 dimension, the axis available to concatenate on is axis = 0. I used axis = 1 and that is out of bounds for the array of dimensions = 1

np.concatenate() is a good tool for combining arrays that are 1D, or multi dimensional

In [59]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "dawi9234/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/dawi9234/numpy-array-operations


'https://jovian.ml/dawi9234/numpy-array-operations'

## Conclusion

In this notebook we explored 5 Numpy functions included in the Numpy library. From here we can use these new Numpy functions for data analysis.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* W3School: https://www.w3schools.com/python/numpy_intro.asp
* geeksforgeeks: https://www.geeksforgeeks.org/

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>